# Generated by Django 4.2.7 on 2023-11-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('phnumber', models.CharField(max_length=15)),
                #('degree', models.CharField(max_length=15)),
                ('first_sem_marks', models.CharField(max_length=3)),
                ('second_sem_marks', models.CharField(max_length=3)),
                ('practical_marks', models.CharField(max_length=3)),
                ('tutorial_marks', models.CharField(max_length=3)),
                #('assignment_marks', models.CharField(max_length=3)),
                ('total_marks', models.CharField(max_length=3)),
            ],
        ),
    ]
